apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-nqam
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0035-tenant/tkrw-pr712-0075-0035-app/devfile-sample-nqam@sha256:fe424ba5035b83bd44564397ec36d5a9f257155433ca8d318419a008ba5adf55
        name: my-nodejs
        resources: {}
status: {}
