apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-nqam
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-nqam
    app.kubernetes.io/part-of: tkrw-pr712-0075-0035-app
  name: devfile-sample-nqam
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-nqam
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-nqam
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0035-tenant/tkrw-pr712-0075-0035-app/devfile-sample-nqam@sha256:fe424ba5035b83bd44564397ec36d5a9f257155433ca8d318419a008ba5adf55
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
